### ISSUE TITLE
is there any possible to support tensorrt 7?

### ISSUE THREAD

**Issue by jcyhcs** [noahmr/yolov5-tensorrt#1]
hi,professor:
is there any possible that with tensorrt 7 work?
please help!

**Comment by noahmr** [comment]
Hi, 

Currently I don't think TensorRT7 is supported, because the Builder class uses some methods that were added in TensorRT8, for instance `buildSerializedNetwork(...)`. But TensorRT7 has alternatives for this, so it shouldn't be too difficult to implement support. I'll look into adding support for it

Just wondering, is there any reason you specifically need TensorRT7 (instead of 8) ?
